# http://www.appveyor.com/docs/appveyor-yml


# version format
version: 0.2.1.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
#    - somebranch

os: Visual Studio 2019
install:
  - set PATH=C:\Program Files (x86)\MSBuild\16.0\Bin;%PATH%


before_build:
  - ps: dotnet tool install --global FlubuCore.Tool --version 5.1.8

build_script:
  - ps: cd BuildScript
  - ps: flubu rebuild -version='{version}'

# to disable automatic tests 
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: src\WickedFlame.Yaml\bin\Release\netstandard2.0\WickedFlame.Yaml.dll
    name: WickedFlame.Yaml.dll

  # pushing all *.nupkg files in directory
  - path: '.\*.nupkg'
  
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# deploy:
    # Deploying to NuGet feed
#  - provider: NuGet
#    server: https://my.nuget.server/feed
#    api_key: 
#      secure: UlhUOcqPXsN837S8VwqMZ+10mKTxkqlnvCS5mwSyUGkFwwukfBtvXNpX81+bjS1j
#    skip_symbols: true
#    symbol_server: https://your.symbol.server/feed
#    artifact: MeasureMap.nupkg